// Generated by the Supabase MCP generate_typescript_types. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id?: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          attribute_schema: Json
          icon: string
          id: number
          name: string
          parent_id: number | null
          position: number
          slug: string
        }
        Insert: {
          attribute_schema?: Json
          icon?: string
          id?: never
          name: string
          parent_id?: number | null
          position?: number
          slug: string
        }
        Update: {
          attribute_schema?: Json
          icon?: string
          id?: never
          name?: string
          parent_id?: number | null
          position?: number
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      cities: {
        Row: {
          id: number
          location: unknown
          name: string
          slug: string
          state: string
        }
        Insert: {
          id?: never
          location: unknown
          name: string
          slug: string
          state: string
        }
        Update: {
          id?: never
          location?: unknown
          name?: string
          slug?: string
          state?: string
        }
        Relationships: []
      }
      conversations: {
        Row: {
          buyer_id: string
          buyer_last_read_at: string | null
          buyer_met_at: string | null
          created_at: string
          id: string
          last_message_at: string
          listing_id: string
          seller_id: string
          seller_last_read_at: string | null
          seller_met_at: string | null
        }
        Insert: {
          buyer_id?: string
          buyer_last_read_at?: string | null
          buyer_met_at?: string | null
          created_at?: string
          id?: string
          last_message_at?: string
          listing_id: string
          seller_id: string
          seller_last_read_at?: string | null
          seller_met_at?: string | null
        }
        Update: {
          buyer_id?: string
          buyer_last_read_at?: string | null
          buyer_met_at?: string | null
          created_at?: string
          id?: string
          last_message_at?: string
          listing_id?: string
          seller_id?: string
          seller_last_read_at?: string | null
          seller_met_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      deals: {
        Row: {
          buyer_confirmed_at: string | null
          buyer_id: string
          conversation_id: string
          created_at: string
          id: string
          listing_id: string
          seller_confirmed_at: string | null
          seller_id: string
        }
        Insert: {
          buyer_confirmed_at?: string | null
          buyer_id: string
          conversation_id: string
          created_at?: string
          id?: string
          listing_id: string
          seller_confirmed_at?: string | null
          seller_id: string
        }
        Update: {
          buyer_confirmed_at?: string | null
          buyer_id?: string
          conversation_id?: string
          created_at?: string
          id?: string
          listing_id?: string
          seller_confirmed_at?: string | null
          seller_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "deals_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: true
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deals_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      favorites: {
        Row: {
          created_at: string
          listing_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          listing_id: string
          user_id?: string
        }
        Update: {
          created_at?: string
          listing_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_images: {
        Row: {
          created_at: string
          height: number | null
          id: number
          listing_id: string
          path: string
          position: number
          thumb_path: string
          user_id: string
          width: number | null
        }
        Insert: {
          created_at?: string
          height?: number | null
          id?: never
          listing_id: string
          path: string
          position?: number
          thumb_path: string
          user_id?: string
          width?: number | null
        }
        Update: {
          created_at?: string
          height?: number | null
          id?: never
          listing_id?: string
          path?: string
          position?: number
          thumb_path?: string
          user_id?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "listing_images_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_images_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          attributes: Json
          bumped_at: string
          category_id: number
          city_id: number
          condition: Database["public"]["Enums"]["item_condition"] | null
          country_code: string
          created_at: string
          currency: string
          demo_image_url: string | null
          description: string
          expires_at: string
          favorites_count: number
          id: string
          is_demo: boolean
          kind: Database["public"]["Enums"]["listing_kind"]
          locality: string | null
          location: unknown
          pincode: string | null
          price_paise: number | null
          price_type: Database["public"]["Enums"]["price_type"]
          report_count: number
          search: unknown
          ships: boolean
          status: Database["public"]["Enums"]["listing_status"]
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          attributes?: Json
          bumped_at?: string
          category_id: number
          city_id: number
          condition?: Database["public"]["Enums"]["item_condition"] | null
          country_code?: string
          created_at?: string
          currency?: string
          demo_image_url?: string | null
          description?: string
          expires_at?: string
          favorites_count?: number
          id?: string
          is_demo?: boolean
          kind?: Database["public"]["Enums"]["listing_kind"]
          locality?: string | null
          location: unknown
          pincode?: string | null
          price_paise?: number | null
          price_type?: Database["public"]["Enums"]["price_type"]
          report_count?: number
          search?: unknown
          ships?: boolean
          status?: Database["public"]["Enums"]["listing_status"]
          title: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          attributes?: Json
          bumped_at?: string
          category_id?: number
          city_id?: number
          condition?: Database["public"]["Enums"]["item_condition"] | null
          country_code?: string
          created_at?: string
          currency?: string
          demo_image_url?: string | null
          description?: string
          expires_at?: string
          favorites_count?: number
          id?: string
          is_demo?: boolean
          kind?: Database["public"]["Enums"]["listing_kind"]
          locality?: string | null
          location?: unknown
          pincode?: string | null
          price_paise?: number | null
          price_type?: Database["public"]["Enums"]["price_type"]
          report_count?: number
          search?: unknown
          ships?: boolean
          status?: Database["public"]["Enums"]["listing_status"]
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          conversation_id: string
          created_at: string
          id: number
          kind: Database["public"]["Enums"]["message_kind"]
          offer_paise: number | null
          offer_state: Database["public"]["Enums"]["offer_state"] | null
          sender_id: string | null
        }
        Insert: {
          body: string
          conversation_id: string
          created_at?: string
          id?: never
          kind?: Database["public"]["Enums"]["message_kind"]
          offer_paise?: number | null
          offer_state?: Database["public"]["Enums"]["offer_state"] | null
          sender_id?: string | null
        }
        Update: {
          body?: string
          conversation_id?: string
          created_at?: string
          id?: never
          kind?: Database["public"]["Enums"]["message_kind"]
          offer_paise?: number | null
          offer_state?: Database["public"]["Enums"]["offer_state"] | null
          sender_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          href: string | null
          id: number
          kind: Database["public"]["Enums"]["notification_kind"]
          read_at: string | null
          title: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          href?: string | null
          id?: never
          kind: Database["public"]["Enums"]["notification_kind"]
          read_at?: string | null
          title: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          href?: string | null
          id?: never
          kind?: Database["public"]["Enums"]["notification_kind"]
          read_at?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_private: {
        Row: {
          id: string
          upi_id: string | null
        }
        Insert: {
          id?: string
          upi_id?: string | null
        }
        Update: {
          id?: string
          upi_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profile_private_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          city_id: number | null
          created_at: string
          deals_count: number
          display_name: string
          id: string
          is_business: boolean
          is_guest: boolean
          role: string
          terms_accepted_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          city_id?: number | null
          created_at?: string
          deals_count?: number
          display_name?: string
          id: string
          is_business?: boolean
          is_guest?: boolean
          role?: string
          terms_accepted_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          city_id?: number | null
          created_at?: string
          deals_count?: number
          display_name?: string
          id?: string
          is_business?: boolean
          is_guest?: boolean
          role?: string
          terms_accepted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          details: string | null
          id: number
          listing_id: string | null
          reason: Database["public"]["Enums"]["report_reason"]
          reported_user_id: string | null
          reporter_id: string
          status: string
        }
        Insert: {
          created_at?: string
          details?: string | null
          id?: never
          listing_id?: string | null
          reason: Database["public"]["Enums"]["report_reason"]
          reported_user_id?: string | null
          reporter_id?: string
          status?: string
        }
        Update: {
          created_at?: string
          details?: string | null
          id?: never
          listing_id?: string | null
          reason?: Database["public"]["Enums"]["report_reason"]
          reported_user_id?: string | null
          reporter_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_user_id_fkey"
            columns: ["reported_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          comment: string | null
          counts: boolean
          created_at: string
          deal_id: string
          friendly: boolean
          id: number
          reliable: boolean
          reviewee_id: string
          reviewer_id: string
        }
        Insert: {
          comment?: string | null
          counts?: boolean
          created_at?: string
          deal_id: string
          friendly: boolean
          id?: never
          reliable: boolean
          reviewee_id: string
          reviewer_id: string
        }
        Update: {
          comment?: string | null
          counts?: boolean
          created_at?: string
          deal_id?: string
          friendly?: boolean
          id?: never
          reliable?: boolean
          reviewee_id?: string
          reviewer_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_deal_id_fkey"
            columns: ["deal_id"]
            isOneToOne: false
            referencedRelation: "deals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_reviewee_id_fkey"
            columns: ["reviewee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_searches: {
        Row: {
          created_at: string
          id: number
          label: string
          query: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          label: string
          query: Json
          user_id?: string
        }
        Update: {
          created_at?: string
          id?: never
          label?: string
          query?: Json
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_searches_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bump_listing: { Args: { p_listing: string }; Returns: string }
      confirm_deal: { Args: { p_deal: string }; Returns: undefined }
      delete_account: { Args: never; Returns: undefined }
      handoff_upi: { Args: { p_conversation: string }; Returns: string }
      is_admin: { Args: never; Returns: boolean }
      is_blocked_between: { Args: { a: string; b: string }; Returns: boolean }
      list_cities: {
        Args: never
        Returns: {
          id: number
          lat: number
          lng: number
          name: string
          slug: string
          state: string
        }[]
      }
      mark_met: { Args: { p_conversation: string }; Returns: undefined }
      mark_read: { Args: { p_conversation: string }; Returns: undefined }
      mark_sold: {
        Args: { p_conversation?: string; p_listing: string }
        Returns: string
      }
      price_hint: { Args: { p_category: number }; Returns: Json }
      profile_public_stats: { Args: { p_user: string }; Returns: Json }
      renew_listing: { Args: { p_listing: string }; Returns: string }
      reputation_level: {
        Args: { deals: number; reliable_raters: number }
        Returns: string
      }
      respond_offer: {
        Args: { p_accept: boolean; p_message: number }
        Returns: undefined
      }
      search_listings: {
        Args: {
          p_category?: string
          p_condition?: Database["public"]["Enums"]["item_condition"]
          p_days?: number
          p_kind?: Database["public"]["Enums"]["listing_kind"]
          p_lat?: number
          p_limit?: number
          p_lng?: number
          p_max_paise?: number
          p_min_paise?: number
          p_offset?: number
          p_price_type?: Database["public"]["Enums"]["price_type"]
          p_q?: string
          p_radius_km?: number
          p_sort?: string
        }
        Returns: {
          category_slug: string
          city: string
          condition: Database["public"]["Enums"]["item_condition"]
          created_at: string
          demo_image_url: string
          distance_km: number
          id: string
          is_demo: boolean
          kind: Database["public"]["Enums"]["listing_kind"]
          locality: string
          price_paise: number
          price_type: Database["public"]["Enums"]["price_type"]
          status: Database["public"]["Enums"]["listing_status"]
          thumb_path: string
          title: string
        }[]
      }
      start_conversation: {
        Args: { p_body: string; p_listing: string }
        Returns: string
      }
      submit_review: {
        Args: {
          p_comment?: string
          p_deal: string
          p_friendly: boolean
          p_reliable: boolean
        }
        Returns: undefined
      }
      unread_counts: { Args: never; Returns: Json }
    }
    Enums: {
      item_condition: "new" | "like_new" | "good" | "fair" | "for_parts"
      listing_kind: "offer" | "wanted"
      listing_status: "active" | "reserved" | "sold" | "paused" | "removed"
      message_kind: "text" | "offer" | "system"
      notification_kind:
        | "message"
        | "offer"
        | "saved_search"
        | "price_drop"
        | "deal"
        | "review"
        | "system"
      offer_state: "pending" | "accepted" | "declined"
      price_type: "fixed" | "negotiable" | "free" | "swap"
      report_reason:
        | "scam"
        | "prohibited"
        | "wrong_category"
        | "duplicate"
        | "offensive"
        | "other"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      item_condition: ["new", "like_new", "good", "fair", "for_parts"],
      listing_kind: ["offer", "wanted"],
      listing_status: ["active", "reserved", "sold", "paused", "removed"],
      message_kind: ["text", "offer", "system"],
      notification_kind: [
        "message",
        "offer",
        "saved_search",
        "price_drop",
        "deal",
        "review",
        "system",
      ],
      offer_state: ["pending", "accepted", "declined"],
      price_type: ["fixed", "negotiable", "free", "swap"],
      report_reason: [
        "scam",
        "prohibited",
        "wrong_category",
        "duplicate",
        "offensive",
        "other",
      ],
    },
  },
} as const
